### PR TITLE
Adding set_auth_token() function

### PR DESCRIPTION
**Pull request by ThabetIbrahim**

### CODE REVIEW

**Comment by rkcudjoe** [comment]
@urkle, do you mind reviewing these before I merge?

**Comment by urkle** [comment]
@rkcudjoe is there no stubbing framework for .NET to stub network requests ?

**Comment by ThabetIbrahim** [comment]
The best thing out there for unit testing in .NET are xunit and moq and as far as i know they don't provide stubbing for network requests.

**Comment by urkle** [comment]
Do all of the network requests go through one single function?  If so you could stub that one function, use a connection object that you can use a mocked version of in the specs.

**Comment by ThabetIbrahim** [comment]
Well yeah they do, ok let me check that out and submit a new pull request.

**Pull request merged**
